/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_HelloNDK */

#ifndef _Included_com_jni_HelloNDK
#define _Included_com_jni_HelloNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_HelloNDK
 * Method:    callFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_HelloNDK_callFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_HelloNDK
 * Method:    callAddFromC
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_HelloNDK_callAddFromC
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_jni_HelloNDK
 * Method:    callStringAppend
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_HelloNDK_callStringAppend
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jni_HelloNDK
 * Method:    callDebugFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_HelloNDK_callDebugFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_HelloNDK
 * Method:    callAddFromJava
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_HelloNDK_callAddFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_HelloNDK
 * Method:    callPrintFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_HelloNDK_callPrintFromJava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
